In [ ]:
import pandas as pd
import numpy as np

df_names = pd.read_csv('./data/names.csv')
display(df_names)
df_drop_last_name = df_names.drop(columns=['last_name'])
display(df_drop_last_name)

   first_name       last_name                           email
0        John             Doe         john-doe@bogusemail.com
1        Mary  Smith-Robinson       maryjacobs@bogusemail.com
2        Dave           Smith        davesmith@bogusemail.com
3        Jane          Stuart       janestuart@bogusemail.com
4         Tom          Wright        tomwright@bogusemail.com
5       Steve        Robinson    steverobinson@bogusemail.com
6      Nicole          Jacobs     nicolejacobs@bogusemail.com
7        Jane          Wright       janewright@bogusemail.com
8        Jane             Doe          janedoe@bogusemail.com
9        Kurt          Wright       kurtwright@bogusemail.com
10       Kurt        Robinson     kurtrobinson@bogusemail.com
11       Jane         Jenkins      janejenkins@bogusemail.com
12       Neil        Robinson     neilrobinson@bogusemail.com
13        Tom       Patterson     tompatterson@bogusemail.com
14        Sam         Jenkins       samjenkins@bogusemail.com
15      Steve          Stuart      stevestuart@bogusemail.com
16     Maggie       Patterson  maggiepatterson@bogusemail.com
17     Maggie          Stuart     maggiestuart@bogusemail.com
18       Jane             Doe          janedoe@bogusemail.com
19      Steve       Patterson   stevepatterson@bogusemail.com
20       Dave           Smith        davesmith@bogusemail.com
21        Sam           Wilks         samwilks@bogusemail.com
22       Kurt       Jefferson    kurtjefferson@bogusemail.com
23        Sam          Stuart        samstuart@bogusemail.com
24       Jane          Stuart       janestuart@bogusemail.com
25       Dave           Davis        davedavis@bogusemail.com
26        Sam       Patterson     sampatterson@bogusemail.com
27        Tom       Jefferson     tomjefferson@bogusemail.com
28       Jane          Stuart       janestuart@bogusemail.com
29     Maggie       Jefferson  maggiejefferson@bogusemail.com
30       Mary           Wilks        marywilks@bogusemail.com
31       Neil       Patterson    neilpatterson@bogusemail.com
32      Corey           Davis       coreydavis@bogusemail.com
33      Steve          Jacobs      stevejacobs@bogusemail.com
34       Jane         Jenkins      janejenkins@bogusemail.com
35       John          Jacobs       johnjacobs@bogusemail.com
36       Neil           Smith        neilsmith@bogusemail.com
37      Corey           Wilks       coreywilks@bogusemail.com
38      Corey           Smith       coreysmith@bogusemail.com
39       Mary       Patterson    marypatterson@bogusemail.com
40       Jane          Stuart       janestuart@bogusemail.com
41     Travis          Arnold     travisarnold@bogusemail.com
42       John        Robinson     johnrobinson@bogusemail.com
43     Travis          Arnold     travisarnold@bogusemail.com

   first_name                           email
0        John         john-doe@bogusemail.com
1        Mary       maryjacobs@bogusemail.com
2        Dave        davesmith@bogusemail.com
3        Jane       janestuart@bogusemail.com
4         Tom        tomwright@bogusemail.com
5       Steve    steverobinson@bogusemail.com
6      Nicole     nicolejacobs@bogusemail.com
7        Jane       janewright@bogusemail.com
8        Jane          janedoe@bogusemail.com
9        Kurt       kurtwright@bogusemail.com
10       Kurt     kurtrobinson@bogusemail.com
11       Jane      janejenkins@bogusemail.com
12       Neil     neilrobinson@bogusemail.com
13        Tom     tompatterson@bogusemail.com
14        Sam       samjenkins@bogusemail.com
15      Steve      stevestuart@bogusemail.com
16     Maggie  maggiepatterson@bogusemail.com
17     Maggie     maggiestuart@bogusemail.com
18       Jane          janedoe@bogusemail.com
19      Steve   stevepatterson@bogusemail.com
20       Dave        davesmith@bogusemail.com
21        Sam         samwilks@bogusemail.com
22       Kurt    kurtjefferson@bogusemail.com
23        Sam        samstuart@bogusemail.com
24       Jane       janestuart@bogusemail.com
25       Dave        davedavis@bogusemail.com
26        Sam     sampatterson@bogusemail.com
27        Tom     tomjefferson@bogusemail.com
28       Jane       janestuart@bogusemail.com
29     Maggie  maggiejefferson@bogusemail.com
30       Mary        marywilks@bogusemail.com
31       Neil    neilpatterson@bogusemail.com
32      Corey       coreydavis@bogusemail.com
33      Steve      stevejacobs@bogusemail.com
34       Jane      janejenkins@bogusemail.com
35       John       johnjacobs@bogusemail.com
36       Neil        neilsmith@bogusemail.com
37      Corey       coreywilks@bogusemail.com
38      Corey       coreysmith@bogusemail.com
39       Mary    marypatterson@bogusemail.com
40       Jane       janestuart@bogusemail.com
41     Travis     travisarnold@bogusemail.com
42       John     johnrobinson@bogusemail.com
43     Travis     travisarnold@bogusemail.com